// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RQuickJs.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "librquickjs_dotnet";





        [DllImport(__DllName, EntryPoint = "init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern RuntimeContext* init();

        [DllImport(__DllName, EntryPoint = "eval", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void eval(RuntimeContext* ctx, byte* script);

        [DllImport(__DllName, EntryPoint = "register", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void register(RuntimeContext* ctx, byte* name, delegate* unmanaged[Cdecl]<void> func);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct RuntimeContext
    {
    }



}
