// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RQuickJs.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "librquickjs_dotnet";





        [DllImport(__DllName, EntryPoint = "init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern RuntimeContext* init();

        [DllImport(__DllName, EntryPoint = "run", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint run(RuntimeContext* ctx, uint a, uint b);

        [DllImport(__DllName, EntryPoint = "csharp_to_rust", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void csharp_to_rust(RuntimeContext* ctx, delegate* unmanaged[Cdecl]<int, int, int> cb);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct RuntimeContext
    {
    }



}
