package rquickjs:wasm;

interface callback-api {
    variant param {
        unit,
        null,
        int(option<s32>),
        str(option<string>),
        vec(option<list<lazy-param>>),
    }

    enum error-code {
        rquickjs,
        eval,
        register,
        todo,
    }

    record callback-error {
        message: string,
        error-code: error-code,
    }

    resource lazy-param {
      constructor(input: param);
      get: func() -> param;
    }

    resource callback {
        invoke: func(name: string, input: list<param>) -> param;
    }
}

interface engine-api {
    use callback-api.{callback, param, callback-error};
    resource engine {
        create: static func() -> result<engine, callback-error>;
        eval: func(script: string) -> result<param, callback-error>;
        register: func(name: string, fn: callback) -> result<_, callback-error>;
    }
}

world rquickjs {
    import callback-api;
    export engine-api;
}
