// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace QuickJsWasm.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "libhost_dotnet";





        [DllImport(__DllName, EntryPoint = "init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern RuntimeContext* init(byte* wasm, nuint length);

        [DllImport(__DllName, EntryPoint = "eval", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void eval(RuntimeContext* ctx, byte* script);

        [DllImport(__DllName, EntryPoint = "register", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void register(RuntimeContext* ctx, byte* name, delegate* unmanaged[Cdecl]<byte*, Param*, nuint, Param*> func);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct RuntimeContext
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ParamList
    {
        public Param* start;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Param
    {
        public ParamTag tag;
        public int int_value;
        public byte* string_value;
        public ParamList list_value;
    }


    internal enum ParamTag : uint
    {
        Unit = 1,
        Int = 2,
        String = 3,
        Null = 4,
        List = 5,
    }


}
