package rquickjs:wasm;

interface callback-api {
    variant param-type {
        unit,
        uint,
    }

    variant param {
        unit,
        uint(u32),
    }

    resource callback {
        params: func() -> list<param-type>;
        invoke: func(input: list<param>) -> param;
    }
}

interface engine-api {
    use callback-api.{callback};
    resource engine {
        constructor();
        eval: func(script: string);
        register: func(name: string, fn: callback);
    }
}

world rquickjs {
    import callback-api;
    export engine-api;
}
