package rquickjs:wasm;

interface callback-api {
    variant param-type {
        int,
    }

    variant param {
        unit,
        int(s32),
        vec(list<lazy-param>),
    }

    resource lazy-param {
      constructor(input: param);
      get: func() -> param;
    }


    resource callback {
        invoke: func(name: string, input: list<param>) -> param;
    }
}

interface engine-api {
    use callback-api.{callback};
    resource engine {
        constructor();
        eval: func(script: string);
        register: func(name: string, fn: callback);
    }
}

world rquickjs {
    import callback-api;
    export engine-api;
}
